Feat / Re-implement Environment Banner
lblod/frontend-organization-portal pull request #420
Opened 2022-12-13 10:00 UTC by iurianu

OP-1927

2022-12-13 10:14 UTC, iurianu commented
The changes added in the first commit were made in 2 different tasks - change button order, and fix double scroll!

2023-01-02 10:31 UTC, nbittich commented
On my machine it looks like this:
Chrome:
![image](https://user-images.githubusercontent.com/3816305/210219293-546342c8-b2ff-47d1-b781-c6e950fb8a56.png)

Firefox:
![image](https://user-images.githubusercontent.com/3816305/210219417-ed0bc114-c2c7-4ecc-97a2-b42606aa553c.png)


It seems that the header "Vlaanderen is het OrganisatiePortaal" is not shown properly?

Same when logged in:
![image](https://user-images.githubusercontent.com/3816305/210219581-0037160c-eb7b-4d7e-a0d8-bdb0fdcd1778.png)

It seems that the name is no longer visible.

2023-01-02 10:32 UTC, nbittich requested changes
it doesn't seem to be displayed properly locally on my machine (see screenshots)

2023-01-13 15:17 UTC, claire-lovisa commented on package.json
> +    "@lblod/ember-environment-banner": "git://github.com/lblod/ember-environment-banner.git#env-banner-op",
Here usually we don't commit that, we wait until the package is released with our changes and we bump it

2023-01-13 15:17 UTC, claire-lovisa commented on app/controllers/application.js
> +  }
Il would also make testing easier, to see how the banner behaves depending on which param we give. Now on localhost it always gets overriden by the localhost value, but I'd be convenient to be able to view the other perspectives of the other envs !

2023-01-13 15:48 UTC, claire-lovisa commented on app/controllers/application.js
> +  }
This is not used anymore no ?

2023-01-13 15:49 UTC, claire-lovisa commented on app/controllers/application.js
> +    return getOwner(this).resolveRegistration('config:environment').appName;
This is not used anymore no ?

2023-01-27 09:48 UTC, claire-lovisa commented
Looks good ! :) I'm just waiting for the addon bump to approve it

2023-01-30 08:12 UTC, claire-lovisa commented
I'm having second thoughts about it. I'm the sure the ember environment detection is reliable enough. I'm not sure it'll be able to detect in which env we are, because for example if you go to dev and use the ember inspector, you can see that the environment detected seems to be prod, even though it's not the case
![image](https://user-images.githubusercontent.com/23281659/215422375-71e023c9-7f63-48a2-9ddc-af96b37e623a.png)

So we probably should go as GN, use environment variables in the docker-compose.override.yml files of dev and qa to set the environment name.

2023-01-30 08:38 UTC, claire-lovisa commented
Indeed, I checked, all built versions of the frontend are built via the `production` configuration so we can't rely on this. So I think the best would be to rely on the `EMBER_ENVIRONMENT_NAME` env variable on the frontend as GN does

2023-01-30 15:54 UTC, claire-lovisa approved these changes

2023-01-30 15:58 UTC, merged