Feat/add fields to core
lblod/frontend-organization-portal pull request #482
Opened 2023-07-07 10:04 UTC by lagartoverde

OP-2342

2023-07-07 14:46 UTC, lagartoverde commented
Converting to draft as I have to add the regio

2023-07-11 08:41 UTC, lagartoverde commented
Ready for review again

2023-07-11 15:38 UTC, claire-lovisa requested changes
Small label issue but appart from that looks good :+1:

2023-07-12 07:08 UTC, claire-lovisa approved these changes

2023-07-12 07:12 UTC, merged