Feature/apb province municipality select filter
lblod/frontend-organization-portal pull request #521
Opened 2023-10-06 11:18 UTC by Dachamelemon

2023-10-06 11:20 UTC, Dachamelemon commented
I tried to fix conflicts before merging but i seem to have made a mistake somewhere you can ignore this prequest

2023-10-09 11:12 UTC, claire-lovisa requested changes
We are also entirely missing the functionality in the `Related organizations` tab of APBs, they can also be edited there, can you add it ? :)

2023-10-09 11:12 UTC, claire-lovisa commented on app/components/administrative-unit-select.hbs
> +    @allowClear={{not @selectedProvince}}
I'm not sure we should enforce that we can clear this component only if there is a selected province. It forces the user of the component to use it together with the province component, which might not be relevant for all the use cases. I think that the responsibility to define whether we should allow the clearing is in the hands of the template/controller calling the component instead

2023-10-09 11:12 UTC, claire-lovisa commented on app/components/administrative-unit-select.js
> +  munipalities = trackedTask(this, this.loadAdministrativeUnitsTask, () => [
Typo in `munipalities` :grin:

2023-10-09 11:12 UTC, claire-lovisa commented on app/components/province-organization-select.hbs
> +    @allowClear={{not @selectedMunicipality}}
Same as for the admin unit component, I think the component should not handle this but the caller should instead

2023-10-09 11:12 UTC, claire-lovisa commented on app/templates/administrative-units/new.hbs
> +                  <AuTextarea
I guess it's an error due to the merge conflict, but we do want to use the `RichTextEditor` component here

2023-10-09 11:12 UTC, claire-lovisa commented on app/templates/administrative-units/administrative-unit/core-data/edit.hbs
> +                      <AuTextarea
I guess it's an error due to the merge conflict, but we do want to use the `RichTextEditor` component here

2023-10-16 06:32 UTC, claire-lovisa requested changes
There are still some behaviours that are broken / changed from the default behaviour of the feature:

- Bestuurseenheden page:
  - broke the auto-select of a province when a gemeente is picked up
  - allowClear on the province should be false when a muncipality is selected
  
Core data, edit page:
  - allowClear on the province should be false when a muncipality is selected
  
Related organizations, edit page:
  - autoselect of a province when a gemeente is picked up doesn't work
  - when a municipality is picked up, we can still chose from all the provinces instead of having only one choice
  - allowClear on the province should be false when a muncipality is selected

2023-10-16 06:32 UTC, claire-lovisa commented on app/templates/administrative-units/administrative-unit/core-data/edit.hbs
> +                        @width="block"
Still has to be rollbacked :)

2023-10-16 06:32 UTC, claire-lovisa commented on app/templates/administrative-units/new.hbs
> +                    @width="block"
same !

2023-10-16 08:19 UTC, claire-lovisa commented
I'm only seeing it now but this behavior should also be added to the `new` route, when a user created a new administrative unit.

2023-10-17 14:00 UTC, claire-lovisa approved these changes
Thank you :smile:

2023-10-17 14:08 UTC, merged