Feat/phonenumber convention sync
lblod/frontend-organization-portal pull request #540
Opened 2023-11-17 10:47 UTC by Dachamelemon

OP-1464

2023-11-17 13:22 UTC, claire-lovisa commented on app/modifiers/inputmaskTel.js
> +    regex: '(\\+)\\d{6}\\d*',
Shouldn't it be 10 instead of 6 ? For the size of a regular belgian phone number

2023-11-20 15:36 UTC, claire-lovisa requested changes
I found an issue I didn't see the first time. If you fill in a number, save the bestuur, then try to re-edit the same page and immediately save, an error will pop up on the phone number saying ` Enkel een plusteken en cijfers zijn toegelaten` even though the number seem to be filled in and formatted correctly

2023-11-20 15:52 UTC, mirdono commented
> I found an issue I didn't see the first time. If you fill in a number, save the bestuur, then try to re-edit the same page and immediately save, an error will pop up on the phone number saying ` Enkel een plusteken en cijfers zijn toegelaten` even though the number seem to be filled in and formatted correctly

The same behaviour seems to be present when trying to save an existing adm. unit location that already had a phone number. If you edit all present phone numbers before saving no such error occurs.

2023-11-30 15:43 UTC, claire-lovisa reviewed
The bug seems fixed ! :) Just need to wait for the backend PR to be ready to merge both at the same time !

2023-11-30 15:43 UTC, claire-lovisa commented on app/controllers/administrative-units/administrative-unit/core-data/edit.js
> +    console.log(contact.telephone);
This can probably go away ? :)

2023-12-04 13:32 UTC, claire-lovisa approved these changes

2023-12-04 13:49 UTC, merged