Feat/integration wegwijs api
lblod/frontend-organization-portal pull request #555
Opened 2023-12-22 14:30 UTC by Dachamelemon

Frontend KBO tab added with temporary static data until backend is ready.

the new class added in _shame.scss should be made option in the Tab component of appuniversum followed up by @oscartison

2024-01-04 15:58 UTC, mirdono requested changes

2024-01-04 15:58 UTC, mirdono commented on app/templates/administrative-units/administrative-unit/core-data/index.hbs
When the KBO tab is selected the edit button remains visible and, when clicked, will redirect the user to the already existing edit page (i.e. the page to edit the ABB data). This is imo confusing from a UX perspective, and is not conform with the proposed design for this page.

2024-01-08 16:04 UTC, mirdono approved these changes

2024-01-09 14:45 UTC, aliokan requested changes
**Blocker** This PR cannot be merged in state. As discuss during standup, the current modifications should be hidden behind feature flag. ;)

2024-01-22 15:31 UTC, aliokan approved these changes
The feature flag integration looks good! :+1:

2024-01-23 10:22 UTC, merged